name: 'Compile Markdown to PDF'

on:
  workflow_dispatch:
jobs:
  md2pdf:
    runs-on: ubuntu-latest
    name: A job to test this action
    env:
      DEFAULT_DESTINATION: 'Example/build/'
      DEFAULT_OUTPUT: output.slides,output.note
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docascod/actions-build@1.0
        with:
          sources: '*.md'
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.DEFAULT_DESTINATION }}/*.pdf
